### ISSUE TITLE
Suggestion for addition

### ISSUE THREAD

**Issue by kwbeck** [mattmon/hue-scene-icons#1]
@mattmon , thank you for these.  I had been looking for a full set of these for a long time.  Much appreciated.

One suggestion, would you add the icon for "Natural Light"?

I made one myself (which I've attached), but it's just photoshopped into a png from a screenshot and not the cleanest.  If you have or can get the one dumped from the app, I'm sure it would be better....

```
scene.*_natural_light:
  entity_picture: /local/hue_scenes/round/natural_light.png
```
![natural_light](https://github.com/mattmon/hue-scene-icons/assets/98544743/62a6c225-a3fe-4cf0-9572-3f2957a25289)

**Comment by mattmon** [comment]
Done.

I also have the rectangular cards dumped from the app as well.

Let me know if you want them!

**Comment by kwbeck** [comment]
Thank you!  Appreciate the offer, but I'm using the round ones, so all good.
